version: '3.8'
services:
  api1:
    image: c-http-api
    build: .
    networks:
      - api-side
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '50 MB'
  api2:
    image: c-http-api
    build: .
    networks:
      - api-side
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '50 MB'

  nginx:
    image: nginx:1.25.3-alpine3.18
    volumes:
      - ./static:/static:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "5555:5555"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '100 MB'
    networks:
      - api-side

networks:
  api-side: {}